language: python
python:
        - "3.5"
        - "3.6"
install:
        - pip install -r requirements.txt

script:
        pytest telegrambot/test/tests.py

deploy:
     -  provider: script
        script: bash .travis/deploy.sh
        on:
                branch: master
                python: '3.5'

     -  provider: script
        script: bash .travis/deploy.sh
        on:
                branch: develop
                python: '3.5'